Add dependencies for building lxml for the snap
lxml is a python dependency of a dependency.

On arm64 and amd64, pip can install the binary wheel,
but these binary wheels aren't available for other architectures.
For them, currently the build fails with:

```
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [4 lines of output]
      <string>:67: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
      Building lxml version 5.2.2.
      Building without Cython.
      Error: Please make sure the libxml2 and libxslt development packages are installed.
      [end of output]
```

So the required build dependencies must be added to the snap definition.