Add dependencies for building cffi for the snap
Binary wheels for the cffi python package aren't available on some
architectures, so we need to add dependencies so pip can build it
from source.

Fixes the following error during snap build:

```
src/c/_cffi_backend.c:15:10: fatal error: ffi.h: No such file or directory
   15 | #include <ffi.h>
      |          ^~~~~~~
compilation terminated.
error: command '/usr/bin/arm-linux-gnueabihf-gcc' failed with exit code 1
[end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
ERROR: Failed building wheel for cffi
```